export const trackingUsers = [
  {
    id: '1',
    name: 'Andi B.',
    initials: 'AB',
    address: 'Jl. Sudirman No. 12',
    updatedAt: 'Updated 2 min ago',
    status: 'online',
    color: 'bg-pink-500',
  },
  {
    id: '2',
    name: 'Siti R.',
    initials: 'SR',
    address: 'Jl. Thamrin No. 45',
    updatedAt: 'Updated 5 min ago',
    status: 'online',
    color: 'bg-amber-500',
  },
  {
    id: '3',
    name: 'Budi D.',
    initials: 'BD',
    address: 'Jl. Gatot Subroto',
    updatedAt: 'Updated 15 min ago',
    status: 'offline',
    color: 'bg-indigo-500',
  },
  {
    id: '4',
    name: 'Hendra H.',
    initials: 'HH',
    address: 'Jl. Kuningan No. 78',
    updatedAt: 'Updated 1 min ago',
    status: 'online',
    color: 'bg-blue-500',
  },
  {
    id: '5',
    name: 'Maya K.',
    initials: 'MK',
    address: 'Jl. Merdeka Barat No. 3',
    updatedAt: 'Updated 30 sec ago',
    status: 'online',
    color: 'bg-emerald-500',
  },
  {
    id: '6',
    name: 'Rizky A.',
    initials: 'RA',
    address: 'Jl. Ahmad Yani No. 58',
    updatedAt: 'Updated 32 min ago',
    status: 'offline',
    color: 'bg-green-600',
  },
];

export const mapMarkers = [
  { id: '1', initials: 'AB', color: 'bg-pink-500', status: 'online', position: [-7.9750, 112.6320] as [number, number] },
  { id: '2', initials: 'SR', color: 'bg-amber-500', status: 'online', position: [-7.9810, 112.6350] as [number, number] },
  { id: '3', initials: 'BD', color: 'bg-indigo-500', status: 'offline', position: [-7.9710, 112.6280] as [number, number] },
  { id: '4', initials: 'HH', color: 'bg-blue-500', status: 'online', position: [-7.9850, 112.6300] as [number, number] },
  { id: '5', initials: 'MK', color: 'bg-emerald-500', status: 'online', position: [-7.9680, 112.6390] as [number, number] },
  { id: '6', initials: 'RA', color: 'bg-green-600', status: 'offline', position: [-7.9900, 112.6250] as [number, number] },
];